#Requires -Version 5.1
<#
.SYNOPSIS
  Writes extensions/arbor/.env and extensions/reroute/.env from the local secrets file.

.DESCRIPTION
  Reads KEY=VALUE lines from the secrets file (default: ~/.browserforge/secrets.env) and emits the
  WXT_* variables the extensions read at build time. Empty keys are skipped so the extension falls
  back to "Licensing not configured". Values are never printed; only key names are reported.

  Keys read (none of them are secrets; they travel in public checkout pages or unauthenticated
  request bodies):

    LICENSE_PROVIDER                    polar | lemonsqueezy (optional; the extension infers it)
    POLAR_ORGANIZATION_ID               Polar dashboard -> Settings -> General
    POLAR_BENEFIT_ID_ARBOR / _REROUTE   Benefits -> <product> licence keys -> copy id
    POLAR_CHECKOUT_URL_ARBOR / _REROUTE https://buy.polar.sh/polar_cl_...
    POLAR_ORG_SLUG                      for the customer-portal link polar.sh/<slug>/portal
    POLAR_SANDBOX_*                     the same four ids/URLs from sandbox.polar.sh (-Sandbox)
    LEMONSQUEEZY_STORE_ID, LEMONSQUEEZY_VARIANT_ID_ARBOR / _REROUTE (kept until the LS path goes)

  POLAR_OAT* (organisation access tokens) are never forwarded: nothing in the extensions needs a
  token, and one must never ship in a build.

.PARAMETER SecretsPath
  Path to the secrets file. Defaults to C:\Users\<you>\.browserforge\secrets.env.

.PARAMETER Sandbox
  Use the POLAR_SANDBOX_* ids and URLs and point the extensions at https://sandbox-api.polar.sh.
  Forces WXT_LICENSE_PROVIDER=polar. For the sandbox test plan only; never ship such a build.

.EXAMPLE
  pwsh scripts/write-env.ps1
  pwsh scripts/write-env.ps1 -Sandbox
  pwsh scripts/write-env.ps1 -SecretsPath C:\tmp\secrets.env
#>
[CmdletBinding()]
param(
  [string]$SecretsPath = (Join-Path $HOME ".browserforge\secrets.env"),
  [switch]$Sandbox
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$polarSandboxApiBase = "https://sandbox-api.polar.sh"

if (-not (Test-Path -LiteralPath $SecretsPath -PathType Leaf)) {
  throw "Secrets file not found: $SecretsPath"
}

# Parse KEY=VALUE lines; ignore blanks and comments; strip one layer of matching quotes.
$secrets = @{}
foreach ($line in Get-Content -LiteralPath $SecretsPath) {
  if ($line -match '^\s*(#|$)') { continue }
  if ($line -match '^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    $key = $matches[1]
    $value = $matches[2].Trim()
    if ($value.Length -ge 2 -and (($value[0] -eq '"' -and $value[-1] -eq '"') -or ($value[0] -eq "'" -and $value[-1] -eq "'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $secrets[$key] = $value
  }
}

function Get-Secret([string]$Key) {
  if ($secrets.ContainsKey($Key)) { return $secrets[$Key] }
  return ""
}

# Polar keys are prefixed POLAR_SANDBOX_ instead of POLAR_ when building against the sandbox.
$polarPrefix = if ($Sandbox) { "POLAR_SANDBOX_" } else { "POLAR_" }
function Get-PolarSecret([string]$Suffix) { return Get-Secret "$polarPrefix$Suffix" }

$products = @(
  @{ Name = "arbor";   Suffix = "ARBOR";   PageUrl = "https://arbor.shantanuojha.com/#pro" },
  @{ Name = "reroute"; Suffix = "REROUTE"; PageUrl = "https://reroute.shantanuojha.com/#pro" }
)

$provider = if ($Sandbox) { "polar" } else { (Get-Secret "LICENSE_PROVIDER").ToLowerInvariant() }
if ($provider -ne "" -and $provider -ne "polar" -and $provider -ne "lemonsqueezy") {
  throw "LICENSE_PROVIDER must be 'polar' or 'lemonsqueezy' (or empty to infer)."
}

$storeId = Get-Secret "LEMONSQUEEZY_STORE_ID"
$organizationId = Get-PolarSecret "ORGANIZATION_ID"
# The slug is not environment-specific in name, but the sandbox organisation may use another one.
$orgSlug = if ($Sandbox -and (Get-Secret "POLAR_SANDBOX_ORG_SLUG") -ne "") { Get-Secret "POLAR_SANDBOX_ORG_SLUG" } else { Get-Secret "POLAR_ORG_SLUG" }
$apiBase = if ($Sandbox) { $polarSandboxApiBase } else { "" }
# LEMONSQUEEZY_TEST_MODE and POLAR_OAT* are intentionally not forwarded: nothing in the extensions reads them.

if ($Sandbox) { Write-Host "Sandbox build: using POLAR_SANDBOX_* ids and $polarSandboxApiBase" }

foreach ($product in $products) {
  $variantId = Get-Secret "LEMONSQUEEZY_VARIANT_ID_$($product.Suffix)"

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by scripts/write-env.ps1 from $(Split-Path -Leaf $SecretsPath). Do not commit.")
  if ($Sandbox) { $lines.Add("# SANDBOX BUILD: talks to $polarSandboxApiBase. Do not ship.") }
  $written = New-Object System.Collections.Generic.List[string]
  $skipped = New-Object System.Collections.Generic.List[string]

  $entries = [ordered]@{
    "WXT_LICENSE_PROVIDER"                             = $provider
    "WXT_POLAR_ORGANIZATION_ID"                        = $organizationId
    "WXT_POLAR_BENEFIT_ID_$($product.Suffix)"          = Get-PolarSecret "BENEFIT_ID_$($product.Suffix)"
    "WXT_POLAR_CHECKOUT_URL_$($product.Suffix)"        = Get-PolarSecret "CHECKOUT_URL_$($product.Suffix)"
    "WXT_POLAR_ORG_SLUG"                               = $orgSlug
    "WXT_POLAR_API_BASE"                               = $apiBase
    "WXT_LEMONSQUEEZY_STORE_ID"                        = $storeId
    "WXT_LEMONSQUEEZY_VARIANT_ID_$($product.Suffix)"   = $variantId
    "WXT_LEMONSQUEEZY_CHECKOUT_URL_$($product.Suffix)" = $product.PageUrl
  }
  foreach ($entry in $entries.GetEnumerator()) {
    if ([string]::IsNullOrWhiteSpace($entry.Value)) { $skipped.Add($entry.Key); continue }
    $lines.Add("$($entry.Key)=$($entry.Value)")
    $written.Add($entry.Key)
  }

  $envPath = Join-Path $repoRoot "extensions\$($product.Name)\.env"
  # UTF-8 without BOM so dotenv parsers see the first key intact.
  [System.IO.File]::WriteAllText($envPath, (($lines -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding $false))

  Write-Host "extensions/$($product.Name)/.env: wrote $($written -join ', ')"
  if ($skipped.Count -gt 0) { Write-Host "  skipped (empty): $($skipped -join ', ')" }
}
