#Requires -Version 5.1
<#
.SYNOPSIS
  Writes extensions/arbor/.env and extensions/reroute/.env from the local secrets file.

.DESCRIPTION
  Reads KEY=VALUE lines from the secrets file (default: ~/.browserforge/secrets.env) and emits the
  WXT_* variables the extensions read at build time. Empty keys are skipped so the extension falls
  back to "Licensing not configured". Values are never printed; only key names are reported.

.PARAMETER SecretsPath
  Path to the secrets file. Defaults to C:\Users\<you>\.browserforge\secrets.env.

.EXAMPLE
  pwsh scripts/write-env.ps1
  pwsh scripts/write-env.ps1 -SecretsPath C:\tmp\secrets.env
#>
[CmdletBinding()]
param(
  [string]$SecretsPath = (Join-Path $HOME ".browserforge\secrets.env")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

if (-not (Test-Path -LiteralPath $SecretsPath -PathType Leaf)) {
  throw "Secrets file not found: $SecretsPath"
}

# Parse KEY=VALUE lines; ignore blanks and comments; strip one layer of matching quotes.
$secrets = @{}
foreach ($line in Get-Content -LiteralPath $SecretsPath) {
  if ($line -match '^\s*(#|$)') { continue }
  if ($line -match '^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    $key = $matches[1]
    $value = $matches[2].Trim()
    if ($value.Length -ge 2 -and (($value[0] -eq '"' -and $value[-1] -eq '"') -or ($value[0] -eq "'" -and $value[-1] -eq "'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $secrets[$key] = $value
  }
}

function Get-Secret([string]$Key) {
  if ($secrets.ContainsKey($Key)) { return $secrets[$Key] }
  return ""
}

$products = @(
  @{ Name = "arbor";   Suffix = "ARBOR";   CheckoutUrl = "https://arbor.shantanuojha.com/#pro" },
  @{ Name = "reroute"; Suffix = "REROUTE"; CheckoutUrl = "https://reroute.shantanuojha.com/#pro" }
)

$storeId = Get-Secret "LEMONSQUEEZY_STORE_ID"
# LEMONSQUEEZY_TEST_MODE is intentionally not forwarded: nothing in the extensions reads it.

foreach ($product in $products) {
  $variantId = Get-Secret "LEMONSQUEEZY_VARIANT_ID_$($product.Suffix)"

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by scripts/write-env.ps1 from $(Split-Path -Leaf $SecretsPath). Do not commit.")
  $written = New-Object System.Collections.Generic.List[string]
  $skipped = New-Object System.Collections.Generic.List[string]

  $entries = [ordered]@{
    "WXT_LEMONSQUEEZY_STORE_ID"                        = $storeId
    "WXT_LEMONSQUEEZY_VARIANT_ID_$($product.Suffix)"   = $variantId
    "WXT_LEMONSQUEEZY_CHECKOUT_URL_$($product.Suffix)" = $product.CheckoutUrl
  }
  foreach ($entry in $entries.GetEnumerator()) {
    if ([string]::IsNullOrWhiteSpace($entry.Value)) { $skipped.Add($entry.Key); continue }
    $lines.Add("$($entry.Key)=$($entry.Value)")
    $written.Add($entry.Key)
  }

  $envPath = Join-Path $repoRoot "extensions\$($product.Name)\.env"
  # UTF-8 without BOM so dotenv parsers see the first key intact.
  [System.IO.File]::WriteAllText($envPath, (($lines -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding $false))

  Write-Host "extensions/$($product.Name)/.env: wrote $($written -join ', ')"
  if ($skipped.Count -gt 0) { Write-Host "  skipped (empty): $($skipped -join ', ')" }
}
